### PR TITLE
Multiple hotkeys for each command

### LINKED ISSUE #3: Extension should allow different hotkey options for different scenarios
Having only one hotkey for each action limits the usability of the extension. Different hotkeys could be desired for when the user is using a mouse and a keyboard or for when the user has both hands on the keyboard.

### PR DESCRIPTION
**Pull request by ortiza5**
This should allow multiple hotkeys to be set for each command.

It also detects if the hotkey is already in use to prevent duplicates. A message popup at the top of the screen lets the user know if it was successful or not.

Closes #3

### CODE REVIEW

**Comment by ortiza5** [comment]
@Pathduck Let me know if you see any bugs I missed or if you think I should change anything. Thanks!

**Comment by Pathduck** [comment]
I just tested this branch, it has some issues - what's going on there? 😄 

image

**Comment by ortiza5** [comment]
Haha, yeah that isn't supposed to happen. Maybe my custom formatter is more fragile than I thought. **What keyboard layout do you use?**

I will have to do some more testing with different keyboard layouts to make sure it is properly formatted.

This is what it looks like on mine:
image

**Comment by ortiza5** [comment]
@Pathduck I had another thought, did you refresh the extension in the extensions page or uninstall and reinstall?

That is necessary because I made a breaking change to how the hotkeys are formatted in storage. This is the new version, but as the first line states, it is only run on installing the extension:
```
chrome.runtime.onInstalled.addListener(function () {
  let settings = {
    hotkeys: {
      codes: {
        navUp: [["w"]],
        navLeft: [["a"]],
        navDown: [["s"]],
        navRight: [["d"]],
        expand: [["e"]],
        contract: [["shift", "e"]],
        quit: [["q"]],
        click: [["f"], ["enter"]],
        shiftClick: [["shift", "enter"]],
        controlClick: [["control", "enter"]],
        disableKeys: [["control", "shift", "x"]],
      },
    },
  };
```

**Comment by ortiza5** [comment]
I am guessing that is the issue because `Contrl`, `Shift`, and `X` got separated into individual hotkeys in the option UI. That would suggest to me that they are set incorrectly in storage as the old:
```
disableKeys: ["control", "shift", "x"],          //without the extra array brackets
```

**Comment by ortiza5** [comment]
I just tested my idea and it does seem to cause the issue you are seeing. So try refreshing the extension or uninstalling and reinstalling.

image


image

**Comment by Pathduck** [comment]
That seems to have been the issue, well done!

**Comment by ortiza5** [comment]
Great! Think it might be safe to merge the pull request now.

I am not super happy with the styling of the notifications on the options page, but that can be changed later.

**Pull request merged**
